// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using skudatabase.MVC.Web.Database;

#nullable disable

namespace skudatabase.MVC.Web.Migrations
{
    [DbContext(typeof(SKUDatabaseContext))]
    [Migration("20250208170926_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("skudatabase.domain.Models.SKU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SKUCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillConfigId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SKUs");
                });

            modelBuilder.Entity("skudatabase.domain.Models.SKUConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SKUConfigs");
                });

            modelBuilder.Entity("skudatabase.domain.Models.SKUConfigSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SKUPartConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SKUConfigSequences");
                });

            modelBuilder.Entity("skudatabase.domain.Models.SKUPartConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowPreceedingZero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAlphaNumeric")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCaseSensitive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RestrictConflictingLettersAndCharacters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SKUConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SKUPartConfigs");
                });

            modelBuilder.Entity("skudatabase.domain.Models.SKUPartValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SKUPartConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SKUPartValues");
                });
#pragma warning restore 612, 618
        }
    }
}
